[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "pydantic-orders"
version = "0.1.0"
description = "Exploring Pydantic for data validation"
dependencies = [
    "pydantic",
    "pandas",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["src"]